version: "2.1"

services:
  app:
    image: golang:1.9-alpine
    volumes:
      - .:/go/src/dailymuse/gzap
    working_dir: /go/src/dailymuse/gzap/integration_tests
    command: go get github.com/dailymuse/gzap && go run main.go
    